#!/usr/bin/env python3
"""Generate the merge-method sweep configs for both tasks from one source.

The method sweep on record ran on the retired Azure generation of experts, so
its recovery fractions are not comparable with anything measured on Isambard -
only the ordering within that table transfers. This regenerates it on the
current generation, and extends it to XSum, which has only ever been merged
linearly.

Each cell is derived from the SAME source config, with only the adapter path
substituted, so the crime and XSum arms of a given method differ in the experts
and in nothing else. Hand-written per-task configs are how this project ended up
unable to say which generation a number came from.
"""
import re
from pathlib import Path

MERGE = Path(__file__).resolve().parent

# method -> the known-good config whose schema we copy. The bare-named configs
# point at the crime adapters, which were retrained at the same paths on
# Isambard, so they are already current.
SOURCES = {
    "linear": "merge_linear_crime_config.yaml",
    "ties": "merge_ties_config.yaml",
    "dare_ties": "merge_dare_ties_config.yaml",
    "slerp": "merge_slerp_config.yaml",
    "task_arithmetic": "merge_task_arithmetic_config.yaml",
    "model_stock": "merge_model_stock_config.yaml",
    "arcee_fusion": "merge_arcee_fusion_config.yaml",
}

HEADER = """\
# GENERATED by merge/make_method_sweep.py - do not edit by hand.
# {method} on the two {task} half-experts, current (Isambard) generation.
#
# Derived from {source} with only the adapter path substituted, so this cell
# and its counterpart on the other task differ in the experts and nothing else.
"""

for method, src_name in SOURCES.items():
    src = MERGE / src_name
    if not src.is_file():
        raise SystemExit(f"missing source config {src_name} - refusing to guess a schema")
    body = src.read_text()
    body = "\n".join(l for l in body.splitlines() if not l.lstrip().startswith("#"))
    body = body.strip() + "\n"

    if "gemma3-crime-" not in body:
        raise SystemExit(f"{src_name} does not reference the crime adapters; "
                         "the naming assumption behind this generator is wrong")

    for task in ("crime", "xsum"):
        out_body, n = re.subn(r"gemma3-crime-", f"gemma3-{task}-", body)
        if n < 2:
            raise SystemExit(f"{src_name}: expected at least two adapter references, found {n}")
        dst = MERGE / f"merge_sweep_{task}_{method}_config.yaml"
        dst.write_text(HEADER.format(method=method, task=task, source=src_name) + out_body)
        print(f"wrote {dst.name}")
