"""Twenty training configs and five merge configs for the four-way crime arm.

Derived from train/crime_gemma1.yaml, changing only the dataset paths, the seed
and the output directory, so the quarter experts differ from the half experts in
nothing but how much data they see. Refuses to write if any other line moves.

Five seeds per quarter, because the question is whether the merge beats the best
shard RELIABLY, and the expert draw is where the variance lives: the five-seed
half study put its standard deviation at 0.0039-0.0049, which is the same size
as the effect being looked for. Pairing by seed licenses a paired test on five
differences rather than a claim resting on one pair.

Linear at 1/4 for the merges: the crowding curve measured that what degrades a
merge is total displacement per direction, and four shard experts all point the
same way, so averaging is the method that is safe by construction here.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRAIN, MERGE = ROOT / "train", ROOT / "merge"
SEEDS, QUARTERS = range(1, 6), range(1, 5)
BASE = "google/gemma-3-4b-it"

src = (TRAIN / "crime_gemma1.yaml").read_text()
for q in QUARTERS:
    for seed in SEEDS:
        body, n_ds = re.subn(r"crime_dataset1", f"crime_dataset_q{q}", src)
        body, n_out = re.subn(r"(?m)^output_dir: .*$",
                              f"output_dir: ../models/gemma3-crime-q{q}-seed{seed}-lora", body)
        if n_ds != 2 or n_out != 1:
            raise SystemExit(f"q{q} seed{seed}: expected 2 dataset lines and 1 output_dir, "
                             f"got {n_ds} and {n_out}; the template has changed")
        if "seed:" in body:
            body = re.sub(r"(?m)^seed: .*$", f"seed: {seed}", body)
        else:
            body += f"\nseed: {seed}\n"
        head = (f"# GENERATED by isambard/make_crime_quarter_configs.py - do not edit by hand.\n"
                f"# Crime quarter {q}, expert seed {seed}. Identical to crime_gemma1.yaml\n"
                f"# except for the dataset, the seed and output_dir.\n")
        (TRAIN / f"crime_gemma_q{q}_seed{seed}.yaml").write_text(head + body)

for seed in SEEDS:
    models = "\n\n".join(
        f'  - model: "{BASE}+../models/gemma3-crime-q{q}-seed{seed}-lora"\n'
        f"    parameters:\n      weight: 0.250000" for q in QUARTERS)
    (MERGE / f"merge_linear_crime_4way_seed{seed}_config.yaml").write_text(
        f"# GENERATED by isambard/make_crime_quarter_configs.py - do not edit by hand.\n"
        f"# Linear merge of the four crime quarter-experts at seed {seed}, weight 1/4.\n"
        f"# All four adapters are the same task and point the same way, so averaging\n"
        f"# holds total displacement at roughly one expert's worth.\n"
        f"merge_method: linear\n\nmodels:\n{models}\n\n"
        f"tokenizer_source: union\n\ndtype: float16\n")
print(f"wrote {len(SEEDS)*len(QUARTERS)} train configs and {len(SEEDS)} merge configs")
