"""Generate the disjoint pair merges of the shard experts.

Between one shard (1/8 of the data) and the full 8-way merge there is a rung
nobody has measured: two shards merged, i.e. 1/4 of the data reached by
averaging rather than by training on it. Pairs are DISJOINT - (1,2), (3,4),
(5,6), (7,8) - so the four pair merges partition the training set exactly once
and can be read as four independent draws of the same quantity, which a
sweep over all 28 pairs could not claim.

Linear at 1/2, for the same reason make_shard_merge.py uses 1/N: the experts
all point the same direction, and what degrades a merge is total displacement
per direction, not adapter count. Averaging holds displacement at roughly one
expert's worth.

    python isambard/make_pair_merges.py --splits 8

writes merge/merge_linear_xsum_pair12_config.yaml ... pair78_config.yaml.
"""
import argparse
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "merge"


def pairs(splits):
    """Disjoint consecutive pairs: (1,2), (3,4), ... Requires an even split."""
    if splits % 2:
        raise SystemExit(f"--splits must be even to pair disjointly, got {splits}")
    return [(i, i + 1) for i in range(1, splits + 1, 2)]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--splits", type=int, required=True)
    ap.add_argument("--base", default="google/gemma-3-4b-it")
    args = ap.parse_args()

    for a, b in pairs(args.splits):
        models = "\n\n".join(
            f'  - model: "{args.base}+../models/gemma3-xsum-{i}-of-{args.splits}-lora"\n'
            f"    parameters:\n      weight: 0.500000"
            for i in (a, b)
        )
        text = (
            f"# GENERATED by isambard/make_pair_merges.py --splits {args.splits}\n"
            f"# Disjoint pair merge of shards {a} and {b} at weight 1/2 - the 1/4-data\n"
            f"# rung between a single shard and the {args.splits}-way merge.\n"
            f"# See the module docstring for why linear and why disjoint.\n"
            f"merge_method: linear\n\nmodels:\n{models}\n\n"
            f"tokenizer_source: union\n\ndtype: float16\n"
        )
        path = OUT / f"merge_linear_xsum_pair{a}{b}_config.yaml"
        path.write_text(text)
        print("wrote", path.name)


if __name__ == "__main__":
    main()
