#!/usr/bin/env python3
"""Derive the pre-fix arm of the alignment A/B from the post-fix arm.

The post-fix arm already exists: crime_kd_distilled_s1..s5, whose results are
results-isambard/crime-distilled-s*.json. Rather than describe a matching arm
and hope it matches, this copies each config verbatim from `base_model:` down
and changes exactly two lines - the teacher dataset and the output directory.
Anything else that differs between the arms would be a confound, and the whole
point of this A/B is that nothing else differs.
"""
import re
from pathlib import Path

TRAIN = Path(__file__).resolve().parent.parent / "train"

HEADER = """\
# GENERATED by isambard/make_crime_legacy_seeds.py - do not edit by hand.
# Crime, distillation from a DELIBERATELY MISALIGNED teacher, seed {seed}.
#
# The pre-fix half of the controlled A/B for 6f923a1. Identical to
# crime_kd_distilled_s{seed}.yaml in every respect - same merge, same seed, same
# kd_alpha 0.0625, same budget - except that the teacher logprobs were written
# by precompute_logprobs.py --legacy-alignment, which emits one row per
# assistant token and no filler. Axolotl then derives input_padding_len = P
# instead of P - 1 and applies every teacher distribution to the token AFTER
# the one it describes.
#
# On a single-token target that is total: the one supervised position gets a
# distribution over a token it does not describe, so the KD term is noise.
#
# WHY THIS EXISTS. The fix's effect had only ever been measured across hardware
# generations - pre-fix numbers from Azure v1 experts, post-fix from Isambard
# v2 - so the inversion it appeared to produce (distilled 0.9707 +/- 0.0011 vs
# control 0.9601 +/- 0.0078 before, distilled 0.9673 +/- 0.0068 vs control
# 0.9725 +/- 0.0011 after) was confounded by the retraining. This arm holds the
# generation fixed and varies only the teacher's row convention.
"""

for seed in range(1, 6):
    src = TRAIN / f"crime_kd_distilled_s{seed}.yaml"
    body = src.read_text()
    start = body.index("base_model:")
    body = body[start:]

    body, n_ds = re.subn(r"(?m)^(\s*- path: .*/crime_kd_train)$",
                         r"\1_legacy", body)
    body, n_out = re.subn(r"(?m)^output_dir: .*$",
                          f"output_dir: ../models/gemma3-crime-kd-legacy-s{seed}",
                          body)
    if n_ds != 1 or n_out != 1:
        raise SystemExit(f"s{seed}: expected 1 dataset and 1 output_dir line, "
                         f"got {n_ds} and {n_out} - refusing to write a config "
                         "that may still point at the aligned teacher")

    dst = TRAIN / f"crime_kd_legacy_s{seed}.yaml"
    dst.write_text(HEADER.format(seed=seed) + body)
    print(f"wrote {dst.name}")
