"""Generate one axolotl config per shard from the existing half-expert config.

train/xsum_gemma1.yaml and xsum_gemma2.yaml differ only in dataset paths and
output_dir - their own header comments say so. Rather than hand-maintain eight
near-identical files (and the drift that invites), this rewrites those three
lines from the shard index and leaves every other hyperparameter exactly as the
halves arm had it, so a shard expert differs from a half expert only in how
much data it saw.

    python isambard/make_shard_configs.py --splits 8

writes train/xsum_gemma_s1_of_8.yaml ... s8_of_8.yaml.
"""
import argparse
import re
from pathlib import Path

TEMPLATE = Path(__file__).resolve().parent.parent / "train" / "xsum_gemma1.yaml"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--splits", type=int, required=True)
    ap.add_argument("--no-4bit", action="store_true",
                    help="drop load_in_4bit, for a host where bitsandbytes "
                         "will not build; record it as a deviation")
    args = ap.parse_args()

    text = TEMPLATE.read_text()
    out_dir = TEMPLATE.parent

    for i in range(1, args.splits + 1):
        body = text
        # The template points at xsum_dataset1; retarget both the train and the
        # validation path in one pass so they cannot drift apart.
        body = re.sub(r"xsum_dataset\d+", f"xsum_dataset{i}", body)
        body = re.sub(
            r"^output_dir:.*$",
            f"output_dir: ../models/gemma3-xsum-{i}-of-{args.splits}-lora",
            body,
            flags=re.M,
        )
        if args.no_4bit:
            body = re.sub(r"^load_in_4bit:.*$", "load_in_4bit: false", body, flags=re.M)
        header = (
            f"# GENERATED by isambard/make_shard_configs.py --splits {args.splits}\n"
            f"# Shard {i} of {args.splits}. Identical to xsum_gemma1.yaml except for\n"
            f"# the dataset paths and output_dir, so the only difference between a\n"
            f"# shard expert and a half expert is how much data it saw.\n"
        )
        path = out_dir / f"xsum_gemma_s{i}_of_{args.splits}.yaml"
        path.write_text(header + body)
        print("wrote", path.name)


if __name__ == "__main__":
    main()
