#!/usr/bin/env python3
"""Five seeds of the crime half-experts, and the merges that compare on them.

WHY. The merge-method sweep reported every method within 0.0065 accuracy of
every other, and the earlier generation's ranking reversed when the experts were
retrained. Both observations are n=1 per cell, which is the standard this
project demands of every other claim and did not meet here.

Merging is DETERMINISTIC - the same adapters under the same method give a
bit-identical model - so there is no seed in the merge. The variance lives in
the experts, which is exactly the report's conclusion. This therefore seeds the
EXPERTS: five independent draws of each half, each merged both ways, compared
paired by seed. That licenses a paired t-test on five differences rather than a
comparison of two single runs.

Crime rather than XSum: its full-versus-best-half gap is fifteen times the
measurement noise where XSum's is under twice, so an effect of this size could
only ever show up on crime.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRAIN, MERGE = ROOT / "train", ROOT / "merge"
import argparse as _argparse
_ap = _argparse.ArgumentParser(description="Generate the crime half-expert seed configs.")
_ap.add_argument("--seeds", nargs="+", type=int, default=list(range(1, 6)),
                 help="expert seeds to generate; the original study used 1-5, and later\nseeds extend it without regenerating what is already trained")
SEEDS = _ap.parse_args().seeds
METHODS = ("linear", "ties")

TRAIN_HEADER = """\
# GENERATED by isambard/make_method_seed_configs.py - do not edit by hand.
# Crime half {half}, expert seed {seed}.
#
# One of five independent draws of this half, so that the merge-method
# comparison can be paired by seed instead of resting on a single pair of
# adapters. Identical to crime_gemma{half}.yaml except for `seed` and
# `output_dir`.
"""

MERGE_HEADER = """\
# GENERATED by isambard/make_method_seed_configs.py - do not edit by hand.
# {method} merge of the crime half-experts at seed {seed}.
#
# Derived from the committed {source}, with only the adapter paths repointed at
# this seed's experts. Both methods merge the SAME two adapters at each seed, so
# the per-seed difference isolates the method.
"""


def main():
    for seed in SEEDS:
        for half in (1, 2):
            src = TRAIN / f"crime_gemma{half}.yaml"
            body = src.read_text()
            body = body[body.index("base_model:"):]
            body, n_out = re.subn(r"(?m)^output_dir: .*$",
                                  f"output_dir: ../models/gemma3-crime-{half}-of-2-seed{seed}-lora",
                                  body)
            if n_out != 1:
                raise SystemExit(f"crime_gemma{half}.yaml: expected one output_dir, got {n_out}")
            if re.search(r"(?m)^seed:", body):
                body = re.sub(r"(?m)^seed: .*$", f"seed: {seed}", body)
            else:
                body = f"seed: {seed}\n" + body
            dst = TRAIN / f"crime_gemma{half}_seed{seed}.yaml"
            dst.write_text(TRAIN_HEADER.format(half=half, seed=seed) + body)
            print(f"wrote {dst.name}")

    for method in METHODS:
        source = ("merge_sweep_crime_linear_config.yaml" if method == "linear"
                  else "merge_sweep_crime_ties_config.yaml")
        src = MERGE / source
        if not src.is_file():
            raise SystemExit(f"missing {source} - generate the sweep configs first")
        base = "\n".join(l for l in src.read_text().splitlines()
                         if not l.lstrip().startswith("#")).strip() + "\n"
        for seed in SEEDS:
            body, n = re.subn(r"gemma3-crime-(\d)-of-2-lora",
                              rf"gemma3-crime-\1-of-2-seed{seed}-lora", base)
            if n < 2:
                raise SystemExit(f"{source}: expected two adapter references, found {n}")
            dst = MERGE / f"merge_seed{seed}_crime_{method}_config.yaml"
            dst.write_text(MERGE_HEADER.format(method=method, seed=seed, source=source) + body)
            print(f"wrote {dst.name}")


if __name__ == "__main__":
    main()
