"""Generate the KD alpha sweep for the 8-shard arm.

Every KD number on record was produced with a misaligned teacher (KD.md,
2026-09-24). The alignment fix (6f923a1) leaves one question open that the
pre-fix data cannot answer: the 0.9/0.1 -> 0.2/1.0 improvement was real, but
the stated explanation - "the weighting was the whole of it" - assumed a
teacher that was in fact scoring the wrong token. Whether a CORRECTLY ALIGNED
teacher at 0.9/0.1 damages the model is untested.

Three points, run against the same student and the same teacher data, answer
it:

    0.9 / 0.1   axolotl's published default, and the setting that produced the
                degeneracy. If the damage was misalignment rather than weight,
                this arm is no longer expected to degenerate.
    0.5 / 0.5   equal nominal weight. Not equal contribution - the KL term is
                the larger of the two by magnitude - but the midpoint that
                separates a monotone trend from a threshold.
    0.2 / 1.0   the measured-magnitude setting, and the one number KD.md still
                treats as standing. Re-run here so all three share a producer.

Derived from train/xsum_gemma_kd_balanced.yaml so every other hyperparameter is
the one the halves arm used; only the weighting, the student, the dataset and
the output directory move.

    python isambard/make_kd_configs.py --splits 8
"""
import argparse
import re
from pathlib import Path

TEMPLATE = Path(__file__).resolve().parent.parent / "train" / "xsum_gemma_kd_balanced.yaml"

# tag -> (kd_alpha, kd_ce_alpha, rationale)
ARMS = {
    "a09": (0.9, 0.1,
            "axolotl's published default. On the misaligned pre-fix run this\n"
            "# produced 40-64 empty outputs and 54-74 with a token repeated three or\n"
            "# more times, out of 1000. With the teacher now scoring the token it\n"
            "# actually describes, this arm is the test of whether that damage was the\n"
            "# weighting or the misalignment."),
    "a05": (0.5, 0.5,
            "Equal nominal weight, not equal contribution: cross-entropy converges\n"
            "# near 1.4 while the top-k KL sits near 8, so this is still roughly 3x more\n"
            "# gradient from the teacher. The midpoint exists to separate a monotone\n"
            "# trend in the weighting from a threshold effect."),
    "a02": (0.2, 1.0,
            "Weights set from the MEASURED loss magnitudes: 0.2 x 8 = 1.6 against\n"
            "# 1.0 x 1.4 puts the two terms within a factor of two. The setting KD.md\n"
            "# still treats as standing, re-run here under the corrected producer so\n"
            "# all three arms share one."),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--splits", type=int, required=True)
    args = ap.parse_args()

    text = TEMPLATE.read_text()
    out_dir = TEMPLATE.parent
    n = args.splits

    # n == 2 is the original halves arm, and its artefacts predate the shard
    # naming: the merge is `gemma3-xsum-merged-linear` and the teacher data is
    # `xsum_kd_train`, with no suffix. Every number in KD.md was measured against
    # those exact paths, so the sweep has to consume them rather than build a
    # parallel `-2way` set that would differ by more than the weighting.
    merge_name = ("gemma3-xsum-merged-linear" if n == 2
                  else f"gemma3-xsum-merged-linear-{n}way")
    kd_data = "xsum_kd_train" if n == 2 else f"xsum_kd{n}_train"

    for tag, (kd_alpha, kd_ce_alpha, why) in ARMS.items():
        body = text
        body = re.sub(r"^base_model:.*$",
                      f"base_model: ../models/{merge_name}",
                      body, flags=re.M)
        body = body.replace("../../datasets/xsum_kd_train",
                            f"../../datasets/{kd_data}")
        body = re.sub(r"^output_dir:.*$",
                      f"output_dir: ../models/gemma3-xsum-kd{n}-{tag}",
                      body, flags=re.M)
        # The template carries the 0.2/1.0 rationale in a comment block. Leaving
        # it on a 0.9/0.1 file would document the opposite of what the file does.
        block = (f"# WEIGHTING ({kd_alpha} / {kd_ce_alpha}). {why}\n")
        body = re.sub(r"# Weighting set from the MEASURED.*?(?=^kd_ce_alpha:)",
                      block, body, flags=re.S | re.M)
        body = re.sub(r"^kd_ce_alpha:.*$", f"kd_ce_alpha: {kd_ce_alpha}", body, flags=re.M)
        body = re.sub(r"^kd_alpha:.*$", f"kd_alpha: {kd_alpha}", body, flags=re.M)

        header = (
            f"# GENERATED by isambard/make_kd_configs.py --splits {n}\n"
            f"# KD onto the {n}-way merge at kd_alpha {kd_alpha} / kd_ce_alpha"
            f" {kd_ce_alpha}.\n"
            f"# One of three arms; see the generator's docstring for the question\n"
            f"# they answer together. Teachers are the {n} shard experts, each over\n"
            f"# its own shard, with the corrected alignment (6f923a1).\n"
        )
        path = out_dir / f"xsum_gemma_kd{n}_{tag}.yaml"
        path.write_text(header + body)
        print(f"wrote {path.name}  (kd_alpha={kd_alpha} kd_ce_alpha={kd_ce_alpha})")


if __name__ == "__main__":
    main()
