#!/usr/bin/env python3
"""Derive the pre-fix arms of the alignment A/B from the post-fix arm.

The post-fix arm already exists: crime_kd_distilled_s1..s5, whose results are
results-isambard/crime-distilled-s*.json. Rather than describe a matching arm
and hope it matches, this copies each config verbatim from `base_model:` down
and changes exactly two lines - the teacher dataset and the output directory.
Anything else that differs between the arms would be a confound, and the whole
point of this A/B is that nothing else differs.
"""
import re
from pathlib import Path

TRAIN = Path(__file__).resolve().parent.parent / "train"

VARIANTS = [
    # (config stem, kd_alpha override or None to inherit 0.0625, why)
    ("legacy", None,
     "at the same 0.0625 / 1.0 as crime_kd_distilled_s{seed}.yaml, which is 1:1\n"
     "# per token"),
    ("legacy_a02", "0.2",
     "at 0.2 / 1.0 - roughly 3:1 per token, and the weighting the Azure arm ran\n"
     "# at when it reported 0.9707 +/- 0.0011 with a teacher that was ALSO\n"
     "# misaligned. Reproducing that cell here holds the generation fixed. If a\n"
     "# misaligned teacher at 3:1 is worse than at 1:1 (0.9214 +/- 0.0327), the\n"
     "# prediction that more weight on a bad signal hurts more holds, and the\n"
     "# Azure figure is simply not reproducible"),
]

HEADER = """\
# GENERATED by isambard/make_crime_legacy_seeds.py - do not edit by hand.
# Crime, distillation from a DELIBERATELY MISALIGNED teacher, seed {seed},
# {why}.
#
# The pre-fix half of the controlled A/B for 6f923a1. Identical to
# crime_kd_distilled_s{seed}.yaml in every respect - same merge, same seed,
# same budget - except for the weighting noted above and the fact that the
# teacher logprobs were written by precompute_logprobs.py --legacy-alignment,
# which emits one row per assistant token and no filler. Axolotl then derives input_padding_len = P
# instead of P - 1 and applies every teacher distribution to the token AFTER
# the one it describes.
#
# On a single-token target that is total: the one supervised position gets a
# distribution over a token it does not describe, so the KD term is noise.
#
# WHY THIS EXISTS. The fix's effect had only ever been measured across hardware
# generations - pre-fix numbers from Azure v1 experts, post-fix from Isambard
# v2 - so the inversion it appeared to produce (distilled 0.9707 +/- 0.0011 vs
# control 0.9601 +/- 0.0078 before, distilled 0.9673 +/- 0.0068 vs control
# 0.9725 +/- 0.0011 after) was confounded by the retraining. This arm holds the
# generation fixed and varies only the teacher's row convention.
"""

for stem, alpha, why in VARIANTS:
    for seed in range(1, 6):
        src = TRAIN / f"crime_kd_distilled_s{seed}.yaml"
        body = src.read_text()
        body = body[body.index("base_model:"):]

        body, n_ds = re.subn(r"(?m)^(\s*- path: .*/crime_kd_train)$",
                             r"\1_legacy", body)
        out = f"gemma3-crime-kd-{stem.replace('_', '-')}-s{seed}"
        body, n_out = re.subn(r"(?m)^output_dir: .*$",
                              f"output_dir: ../models/{out}", body)
        n_a = 1
        if alpha is not None:
            body, n_a = re.subn(r"(?m)^kd_alpha: .*$", f"kd_alpha: {alpha}", body)
        if n_ds != 1 or n_out != 1 or n_a != 1:
            raise SystemExit(
                f"{stem} s{seed}: expected one dataset, one output_dir and one "
                f"kd_alpha line, got {n_ds}, {n_out} and {n_a} - refusing to "
                "write a config that may still point at the aligned teacher or "
                "carry the wrong weighting")

        dst = TRAIN / f"crime_kd_{stem}_s{seed}.yaml"
        dst.write_text(HEADER.format(seed=seed, why=why) + body)
        print(f"wrote {dst.name}")
