"""Generate the N-way linear merge config for the shard experts.

Linear at 1/N, deliberately. The crowding curve measured that what degrades a
merge is total displacement per direction, not the number of adapters: three
adapters under task-arithmetic at weight 1.0 dropped crime accuracy to 0.5348,
below the untuned base model, while TIES lost 0.019. Eight shard experts all
point the same way, so averaging - which holds total displacement at roughly
one expert's worth - is the only method that is safe by construction here.
Anything that adds whole task vectors would apply eight doses of one direction.

    python isambard/make_shard_merge.py --splits 8
"""
import argparse
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "merge"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--splits", type=int, required=True)
    ap.add_argument("--base", default="google/gemma-3-4b-it")
    args = ap.parse_args()

    weight = 1.0 / args.splits
    models = "\n\n".join(
        f'  - model: "{args.base}+../models/gemma3-xsum-{i}-of-{args.splits}-lora"\n'
        f"    parameters:\n      weight: {weight:.6f}"
        for i in range(1, args.splits + 1)
    )
    text = (
        f"# GENERATED by isambard/make_shard_merge.py --splits {args.splits}\n"
        f"# Linear merge of {args.splits} shard experts at weight 1/{args.splits}.\n"
        f"# See the module docstring for why linear and not task-arithmetic.\n"
        f"merge_method: linear\n\nmodels:\n{models}\n\n"
        f"tokenizer_source: union\n\ndtype: float16\n"
    )
    path = OUT / f"merge_linear_xsum_{args.splits}way_config.yaml"
    path.write_text(text)
    print("wrote", path)


if __name__ == "__main__":
    main()
